services:

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: task-backend
    environment:
      DB_HOST: db
      DB_NAME: tasks
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: task-db
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: